# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DLAttributedString_Demo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for DLAttributedString_Demo
pod 'DLAttributedString', '~>0.0.2'
  target 'DLAttributedString_DemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DLAttributedString_DemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
